### ISSUE TITLE
Issue in sharing driver with other class

### ISSUE THREAD

**Issue by qatestingravi** [serenity-bdd/serenity-cucumber6#26]
I want to share driver object to other class.  For example, I have created some common methods in 'SeleniumLib' class.  

I have created constructor in homepage and passing driver to 'SeleniumLib' class. After that trying to use 'SeleniumLib' class, but it throws null pointer. Can you please help me to share the driver object in "SeleniumLib" class.

Steps to reproduce:
1. Pull the project from below github url
https://gitlab.com/alltempprojects/tempuiwebjvjunitcucumberserenityv2
2.Run VerifySearchInHomePage.feature
Observe that, "When User enter "T-shirt" in search box" step is failed due to driver is null

Expected:
step should run successfully

Actual:
Getting null pointer exception for driver

Console log:
C:/Users/DELL/IdeaProjects/AllProjects/AllTempProjects/TempUIWebJVJunitCucumberSerenityV2/src/test/resources/features/VerifySearchInHomePage.feature
Before --> Tue Mar 16 12:42:05 IST 2021 --> Thread id: 1 --> Verify Search in Home Page
Navigated to shop.edzotech home page
03-16-2021 12:42:05.603 [main] INFO  n.s.c.w.d.ChromeDriverProvider - Using automatically driver download
03-16-2021 12:42:05.798 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Using chromedriver 89.0.4389.23 (resolved driver for Chrome 89)
03-16-2021 12:42:05.821 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\DELL\.cache\selenium\chromedriver\win32\89.0.4389.23\chromedriver.exe
03-16-2021 12:42:06.286 [main] INFO  n.s.c.w.d.ProvideNewDriver - Instantiating driver
03-16-2021 12:42:06.286 [main] INFO  n.s.c.w.d.ProvideNewDriver - Driver capabilities: Capabilities {acceptInsecureCerts: false, browserName: chrome, goog:chromeOptions: {args: [], extensions: []}, loggingPrefs: org.openqa.selenium.logging...}
Starting ChromeDriver 89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}) on port 40573
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Mar 16, 2021 12:42:07 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
java.lang.NullPointerException
	at utilities.SeleniumLib.sendKeys(SeleniumLib.java:28)
	at pages.HomePage.enterSearchBox(HomePage.java:24)
	at stepdefinitions.VerifySearchInHomePageStepDef.userEnterInSearchBox(VerifySearchInHomePageStepDef.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:66)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
	at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
	at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:63)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:92)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:63)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:49)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:99)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:71)
	at io.cucumber.core.runtime.Runtime.lambda$execute$5(Runtime.java:110)
	at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:117)
	at io.cucumber.core.runtime.Runtime.lambda$execute$6(Runtime.java:110)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:233)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:86)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)
	at io.cucumber.core.cli.Main.run(Main.java:79)
	at io.cucumber.core.cli.Main.main(Main.java:33)

**Comment by wakaleo** [comment]
I can't see the repo you are referring to. Why don't you just use the Serenity managed driver?

**Comment by qatestingravi** [comment]
@wakaleo can you please check it now, earlier repo was private, now changed to public, I need to use some custom logs, that's the reason why not using managed driver.

**Comment by qatestingravi** [comment]
@wakaleo Did you get a chance to look at it?

**Comment by qatestingravi** [comment]
@wakaleo can you please guide me to resolve above issue. my goal is to share methods which is defined in one class to another class. The class which I want to share have only my custom methods,  not steps.

**Comment by qatestingravi** [comment]
closing for now
